### ISSUE TITLE
Delegation from campaign to milestone throws error

### ISSUE THREAD

**Issue by satyavh** [Giveth/feathers-giveth#65] opened 2017-12-06 09:45 UTC
Reproduce:

1. donate to campaign
2. go to delegations
3. delegate to milestone

This will fail both locally as well as on alpha. The error in the browser console is:

```
"Error: the tx doesn't have the correct nonce. acco…les/ethereumjs-testrpc/build/cli.node.js:81513:3)", code: -32000}
code: -32000
message: "Error: the tx doesn't have the correct nonce. account has nonce of: 15 tx has nonce of: 14↵
```

no errors in feathers / testrpc

**Comment by perissology** [comment] 2017-12-07 16:13
if you refresh the page, I think it'll work. I've seen that error before, and a refresh worked.

I can't reproduce this exact scenario locally.

I think this is related to #61

**Comment by perissology** [comment] 2018-07-02 19:40
The nonce errors should be fixed

**Closed by perissology** 2018-07-02 19:40 UTC
